# docker-compose.override.yml
services:
  template_app: # Make sure this matches the name in docker-compose.yml
    ports:
      - "8125:8000"
    volumes:
      - ./backend:/app/backend
      - ./backend/media:/app/backend/media
    environment:
      - ENV_TYPE=local


  db:
    ports:
      - "5435:5432"

# -----------------------------------------------------------
# OVERRIDE NETWORKS
# -----------------------------------------------------------
networks:
  proxy:
    # This disables the 'external: true' setting from the base file
    external: false
    name: project_template_local_proxy