version: "3.9"

services:
  project_template_app:
    ports:
      - "8125:8000"
    volumes:
    #  - ./backend:/app/backend
    - ./backend/media:/app/backend/media
    environment:
      - ENV_TYPE=development

  db:
    ports:
      - "5435:5432"
    networks:
      - app-network

networks:
  proxy: {}
