services:
  backend:
    ports:
      - "8125:8000"
    volumes:
      - ./backend/media:/app/backend/media
      
      # WICHTIG: Das hier ist dein "Live-Link".
      # Es mountet den Ordner ../webapp-management über die kopierten Dateien im Container.
      # Änderungen im Code sind sofort sichtbar, ohne Rebuild.
      - ../webapp-management:/app/backend/webapp-management
    
    environment:
      - ENV_TYPE=local
      - TRAEFIK_ROUTER_RULE=Host(`localhost`)
    
    # Pip install im Editable Mode (-e), damit Python die Änderungen auch akzeptiert
    command: >
      sh -c "pip install -e ./webapp-management && 
             daphne -b 0.0.0.0 -p 8000 project_template_app.asgi:application"

  db:
    ports:
      - "5435:5432"

networks:
  proxy:
    external: false
    name: project_template_local_proxy

volumes:
  postgres_data:
    external: false
    name: ${DB_VOLUME_NAME:-local_postgres_data}
  media_volume:
    external: false
    name: ${MEDIA_VOLUME_NAME:-local_media_volume}