services:
  backend:
    image: ghcr.io/ihr-user/jg-backend:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: ${CONTAINER_NAME_PREFIX}_backend
    env_file:
      - .env
    depends_on:
      - db
      - redis
    environment:
      - REDIS_HOST=${CONTAINER_NAME_PREFIX}_redis
    volumes:
      - media_volume:/app/backend/media
    networks:
      - app-network
      - proxy
    # HIER KEINE Map mehr, entweder gar kein secrets: oder als Liste:
    # secrets:
    #   - npmrc        # nur nötig, wenn du das Secret im laufenden Container brauchst

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${ROUTER_NAME}.rule=${TRAEFIK_ROUTER_RULE}"
      - "traefik.http.routers.${ROUTER_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${ROUTER_NAME}.tls.certresolver=myresolver"
      - "traefik.http.services.${ROUTER_NAME}.loadbalancer.server.port=8000"
    restart: unless-stopped

  db:
    image: postgis/postgis:14-3.1
    container_name: ${CONTAINER_NAME_PREFIX}_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: ${CONTAINER_NAME_PREFIX}_redis
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
  proxy:
    external: true
    name: traefik_proxy

volumes:
  # Names are now injected via .env generated by the python script
  postgres_data:
    external: true
    name: ${DB_VOLUME_NAME}
  
  media_volume:
    external: true
    name: ${MEDIA_VOLUME_NAME}
