# Generated by Django 5.2.8 on 2025-11-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('supervisor', 'Supervisor'), ('collaborator', 'Collaborator'), ('none', 'None')], default='none', max_length=20),
        ),
    ]
