# Generated by Codex on 2026-03-16

import django.db.models.deletion
import django.utils.timezone
import django_core_micha.auth.roles
import uuid
from django.conf import settings
from django.db import migrations, models


def create_default_auth_policy(apps, schema_editor):
    auth_policy_model = apps.get_model("users", "AuthPolicy")
    auth_policy_model.objects.update_or_create(
        pk=1,
        defaults={
            "allow_admin_invite": True,
            "allow_self_signup_access_code": True,
            "allow_self_signup_open": False,
            "allow_self_signup_email_domain": False,
            "allow_self_signup_qr": False,
            "allowed_email_domains": [],
            "required_auth_factor_count": 1,
            "signup_qr_expiry_days": 90,
        },
    )


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_userprofile_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="uuid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="language",
            field=models.CharField(default="en", max_length=10),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_invited",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_support_agent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="support_contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supported_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("collaborator", "Collaborator"),
                    ("supervisor", "Supervisor"),
                    ("admin", "Admin"),
                ],
                default=django_core_micha.auth.roles.get_default_role_code,
                max_length=64,
            ),
        ),
        migrations.CreateModel(
            name="AuthPolicy",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("allow_admin_invite", models.BooleanField(default=True)),
                ("allow_self_signup_access_code", models.BooleanField(default=False)),
                ("allow_self_signup_open", models.BooleanField(default=False)),
                ("allow_self_signup_email_domain", models.BooleanField(default=False)),
                ("allow_self_signup_qr", models.BooleanField(default=False)),
                ("allowed_email_domains", models.JSONField(blank=True, default=list)),
                ("required_auth_factor_count", models.PositiveSmallIntegerField(default=1)),
                ("signup_qr_expiry_days", models.PositiveIntegerField(default=90)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"abstract": False},
        ),
        migrations.RunPython(create_default_auth_policy, migrations.RunPython.noop),
    ]
