# Generated by Django on 2026-05-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_authpolicy_admin_required_auth_factor_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='authpolicy',
            name='access_code_single_use',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='authpolicy',
            name='require_email_verification',
            field=models.BooleanField(default=False),
        ),
    ]
